# Generated by Django 5.2 on 2025-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('game_dev', 'Game Development'), ('cloud', 'Cloud Computing'), ('devops', 'DevOps & Automation'), ('software', 'Software Engineering'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
